version: '2'
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  mongoweb:
    restart: always
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
            - "8081:8081"
  backend:
    container_name: backend
    build: backend
    ports:
      - "8080:8080"

